(draft) feat: track availability of the transports
Programming6-projects/LosCuriosos pull request #21
Opened 2024-09-17 18:59 UTC by JeferssonCL

…r type int?

# Pull Request

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality
      to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-09-17 18:59 UTC, JorgeHB69 commented
Task linked: [CU-8689n1gr4 Track availability of the transports (Endpoints)](https://app.clickup.com/t/8689n1gr4)

2024-09-19 03:49 UTC, JorgeHB69 requested changes

2024-09-19 03:49 UTC, JorgeHB69 commented on src/DistributionCenter.Infraestructure/DTOs/Concretes/Transports/UpdateTransportDto.cs
> +        entity.Plate = Plate ?? entity.Plate;
The plate should be editable?

2024-09-19 10:36 UTC, Miguelito2774 commented
POST

1. When adding a transport, the JSON rewrites all existing data, generating duplicates of all registered transports.
2. There is no validation to avoid repeating plates between transports.
3. Transport names can be repeated without restrictions.
4. It is possible to assign incorrect capacities to transports, such as adding a van with the capacity of a truck and vice versa.

PUT

1. Currently, editing of a transport's nameplate is allowed. It would be more appropriate to limit edits to capacity and availability, leaving the nameplate and name uneditable.
2. When trying to edit the capacity with a decimal value (when it should be an integer), the system displays a user-unfriendly technical message: “The JSON value could not be converted to System.Nullable\1[System.Int32]. Path: $.capacity | LineNumber: 3 | BytePositionInLine: 17.
3. After a successful edit, the displayed message could be clearer, I suggest using: “Transport edited successfully.”

PATCH

1. In case of trying to deactivate a transport that is already deactivated, a message should be displayed that clearly indicates this situation, such as, “Transport is already deactivated.”
2. After successfully deactivating a transport, the displayed message could be upgraded to: “Transport successfully deactivated.”

2024-09-19 11:21 UTC, JeferssonCL commented on src/DistributionCenter.Infraestructure/DTOs/Concretes/Transports/UpdateTransportDto.cs
> +        entity.Plate = Plate ?? entity.Plate;
Sip porque no?

2024-09-20 02:49 UTC, JeferssonCL commented on src/DistributionCenter.Infraestructure/DTOs/Concretes/Transports/UpdateTransportDto.cs
> +        entity.Plate = Plate ?? entity.Plate;
Done

2024-09-20 02:50 UTC, JeferssonCL commented on src/DistributionCenter.Infraestructure/DTOs/Concretes/Transports/UpdateTransportDto.cs
> +        entity.Plate = Plate ?? entity.Plate;
Done

2024-09-20 14:10 UTC, Miguelito2774 approved these changes, later dismissed
Now yes, good job.

2024-09-20 14:23 UTC, aguirrekarina approved these changes, later dismissed
Good job

2024-09-20 14:31 UTC, MorveN11 approved these changes
Good Job @JeferssonCL

2024-09-20 14:31 UTC, MorveN11 commented on src/DistributionCenter.Domain/DistributionCenter.Domain.csproj
Why is necessary add commons to the Domain?

2024-09-20 14:32 UTC, JorgeHB69 approved these changes

2024-09-20 14:32 UTC, Miguelito2774 approved these changes

2024-09-20 14:32 UTC, merged